### ISSUE TITLE
unable to build. missing reference files.

### ISSUE THREAD

**Issue by Benchwork** [gindyo/WhatAreYouDoing#8]
I found your app, tested it, liked it, and wanted to try and build it... but it is missing some reference files. Castle.Core & Castle.Windsor I'm hoping to find a way to resolve these so that I can try and build it.  I have been looking for something like this for a while!!   

also I didn't see a published license type so I hope me doing this is ok.

Peter.

**Comment by Benchwork** [comment]
resolved myself. thank you anyway

**Comment by gindyo** [comment]
Hi Peter,
i just saw your email. Im glad you liked the app. I built it purely for my
use and never thought about licensing it.  Please feel free to use and
modify it to your liking.
